### PR TITLE
Add a retry mechanism on all API calls

### PR DESCRIPTION
**Pull request by z8v**
The PR simply adds the `retry` package and wraps all the API calls with a retry mechanism.

### CODE REVIEW

**Comment by xtermi2** [comment]
Is here any progress? We need this retry mechanism because he have a lot of failures which could be solved by retries 🙏

**Comment by z8v** [comment]
@xtermi2 The repo seems abandoned. I think the best way forward would be to fork and apply any patches you need.

**Comment by xtermi2** [comment]
Thanks, I've also noticed https://gitlab.com/marge-org/marge-bot which should be the future of marge bot

**Comment by nejch** [comment]
Hey @z8v @xtermi2! Yes, we're trying to revive this project on GitLab.com. Feel free to follow/star that project :)

This PR was imported during the community fork migration as https://gitlab.com/marge-org/marge-bot/-/merge_requests/349.

However, see also https://gitlab.com/marge-org/marge-bot/-/issues/375 for what I personally think might be a more maintainable approach that fixes other issues.

**Pull request closed without merging**
