### PR TITLE
Catch exception from early attempt to parse json in response

### PR DESCRIPTION
**Pull request by benjamb**
Currently attempts to log response.json() before verifying response status.

### CODE REVIEW

**Comment by benjamb** [comment]
Wasn't certain whether or not I should just remove the debug statement?

**Comment by aschmolck** [comment]
Did you encounter an API response that wasn't valid json in practice, and when did it happen? 

I think if this happens in practice,  we probably still want the to debug log the response body. Maybe the simplest solution wold be to just always print response.text (or if we feel paranoid, response.content) instead.

**Comment by benjamb** [comment]
@aschmolck Yes. We've been hitting 503 errors. I'm not sure of the content of the response, only that an exception was thrown at this point.

Further down, when raising an exception against unrecognised response codes, the same try/except block is used. Should I update this patch to simply change `response.json()` to `response.text`?

**Comment by aschmolck** [comment]
@benjamb you mean this bit, right?
```
        try:
            err_message = response.json()
        except json.JSONDecodeError:
            err_message = response.reason
```
Yeah, I think replacing both instances by `response.text` and getting rid of the try/except should probably be fine.

**Comment by benjamb** [comment]
@aschmolck Cheers for sorting this out!

**Comment by aschmolck** [comment]
@benjamb no problem: thanks for reporting bugs and submitting PRs!

**Pull request closed without merging**
