### PR TITLE
URL encode branch names

### PR DESCRIPTION
**Pull request by benjamb**
Otherwise this will error if the branch contains a '/'.

### CODE REVIEW

**Comment by benjamb** [comment]
Note in the API wrt branch/tag name encoding: https://docs.gitlab.com/ee/api/README.html#branches-amp-tags-name-encoding

**Comment by jcpetruzza** [comment]
Good catch! Could you maybe add also a test-case for this in `test_commit.py`?

**Comment by benjamb** [comment]
@jcpetruzza Will that do? Or would you prefer I adapt the existing test to cover this case?

**Comment by jcpetruzza** [comment]
@benjamb It was perfect that way. Will make a new release, hopefully, later today

**Comment by jcpetruzza** [comment]
Version 0.3.2 released

**Pull request merged**
